name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure || true  # no tests yet, don't fail
